### GET ALL IDS
GET http://localhost:8080/getAll


### GET BY ID
GET http://localhost:8080/getOne/1

### SIGN UP
POST http://localhost:8080/post
Content-Type: application/json

{
  "id":"2",    
  "email":"lokesh",    
  "password":"123456",    
  "name":"Loke",    
  "phn":"9768994954"  
}

### UPDATE BY ID
PUT http://localhost:8080/update/3
Content-Type:application/json

{
   "id":"1",    
  "email":"lokeshKumar@gmail.com",    
  "password":"123456",    
  "name":"Nithiah",    
  "phn":"9768994954"    
}

// Api for Bill

### POST BILL
POST http://localhost:8080/bill
Content-Type: application/json

{
     "id":12,
     "name":"pharcetamol",
     "description":"fever",
     "price":5.0,
     "quantity":2
}

### GET BY ID
GET http://localhost:8080/searchid/11


### GET ALL BILL
GET http://localhost:8080/getbill

### DELETE BY ID
DELETE http://localhost:8080/delete/1